version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - notes-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 60s

  django:
    build:
      context: . 
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    networks: 
      - notes-app
    env_file:
      - ".env"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      retries: 5
      start_period: 60s

networks:
  notes-app:
#THIS CREATES THE OWN NETWORK ON BUILDING...

volumes:
  mysql-data:
#THIS CREATES THE OWN volume ON BUILDING... no need to externally make it 
  #external: true   # ← Docker will NOT create this, expects it to already exist
#django-notes-app_mysql-data